# Generated by Django 6.0.6 on 2026-06-26 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair", models.CharField(max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("BUY", "BUY"), ("SELL", "SELL")], max_length=10
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=5, max_digits=20)),
                ("sl", models.DecimalField(decimal_places=5, max_digits=20)),
                ("tp1", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "tp2",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=20, null=True
                    ),
                ),
                (
                    "tp3",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=20, null=True
                    ),
                ),
                ("confidence_score", models.IntegerField()),
                ("setup_type", models.CharField(max_length=50)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reasoning", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("BASIC", "BASIC"),
                            ("PREMIUM", "PREMIUM"),
                            ("TRIAL", "TRIAL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entry_price", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "pnl_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signals.signal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
